Met à jour les boutons de clôture d'un besoin
betagouv/place-des-entreprises pull request #1215
Opened 2020-08-26 12:36 UTC by LucienMLD

closes #1202

2020-08-26 14:32 UTC, n-b requested changes
Je pense qu’il y a des trucs à ajuster dans `Need` aussi, en particulier `#by_status`, non?

2020-08-26 14:32 UTC, n-b commented on app/models/match.rb
> +  }, _prefix: true
Hu, ça serait pas le moment de se mettre à utiliser des enum postgresql? https://github.com/bibendi/activerecord-postgres_enum a l’air d’être largement utilisé par plein de monde.

(et puis c’est pas aligné :p)

2020-08-26 14:32 UTC, n-b commented on app/models/diagnosis.rb
> +      .merge(Match.done)
`min_closed_at` est utilisé pour dans le CompanyMailerService pour envoyer le mail de satisfaction et d’inscription à la newsletter. Si on utiliser Match.done, qui inclut les done_not_reachable, on va envoyer des emails de satisfaction aux entreprises à qui on a pas pu proposer de solution. C’est un peu la loose?

En fait j’ai un problème avec Match.done qui inclut autre chose que le status `done`; au moins le scope devrait s‘appeler autrement.

2020-08-26 14:32 UTC, n-b commented on app/helpers/status_helper.rb
> +    done_not_reachable: %w[teal]
Tu peux garder green pour les trois boutons, mais en basic/outline pour les done “échoués”. Ça fera moins 🎄, déjà

2020-08-27 12:43 UTC, LucienMLD commented on app/helpers/status_helper.rb
> +    done_not_reachable: %w[teal]
On avait pas dit qu'on gardait les outline pour les labels ? 😬

2020-08-27 12:46 UTC, n-b commented on app/helpers/status_helper.rb
> +    done_not_reachable: %w[teal]
je sais pas, les circonstances ont changé 🤷

2020-08-27 12:46 UTC, LucienMLD commented on app/models/match.rb
> +  }, _prefix: true
Ca changerait quoi d'utiliser les enum postgresql ?
Pour l'alignement c'est bizarre oui.

2020-08-27 12:53 UTC, n-b commented on app/models/match.rb
> +  }, _prefix: true
Principalement, ça nous garantit qu’il n’y a pas de valeurs impossibles en base, aujourd’hui ça pourrait être n'importe quel integer; en plus, ça découple de la valeur de l’enum de sa valeur numérique, on a plus besoin de savoir que “not_for_me” vaut 3, ce n'est même d’ailleurs plus le cas.

2020-08-27 12:54 UTC, LucienMLD commented on app/models/diagnosis.rb
> +      .merge(Match.done)
En fait en relisant je m'aperçois que ça n'a pas trop de sens ce changement. Autant laisser `.merge(Match.status_done)` ce scope n'a pas d'autre utilité que d'envoyer les emails

2020-09-01 09:00 UTC, n-b approved these changes
Bon, il faut qu’on fasse quelque chose pour les boutons, mais j'imagine qu’on verra plus clair une fois qu’on s’en sera servi en prod :D

2020-09-01 09:01 UTC, merged