Add missing reverse associations
betagouv/place-des-entreprises pull request #1422
Opened 2020-11-30 13:27 UTC by n-b

rails-erd prints out some warnings when building the diagram pdf. Ideally we’d plug it into the linter, but I don’t think it’s easily feasible.

2020-11-30 16:12 UTC, LucienMLD approved these changes

2020-12-02 09:05 UTC, clairezed commented on app/models/solicitation.rb
> +  has_many :matches, through: :diagnoses, inverse_of: :solicitation
elle est déjà au-dessus, celle-là...

2020-12-02 09:16 UTC, clairezed requested changes
association en doublon à supprimer

2020-12-02 09:16 UTC, clairezed commented on app/models/solicitation.rb
> +  has_many :matches, through: :diagnoses, inverse_of: :solicitation
```suggestion
```

2020-12-02 09:18 UTC, clairezed approved these changes

2020-12-02 09:23 UTC, merged