ne permets plus les doublons de responsables d'antenne
betagouv/place-des-entreprises pull request #2396
Opened 2022-04-06 08:53 UTC by LucienMLD

closes #2395

2022-04-08 07:36 UTC, clairezed commented on app/models/antenne.rb
> +  has_many :managers, -> { distinct }, through: :user_rights_manager, source: :user, inverse_of: :managed_antennes
ça ne suffit pas ; là tu gères l'affichage, mais l'objet (UserRight) est quand même créé derrière.

Ce que je vois à revoir (y'a peut-être d'autres trucs) : 
- ajouter une contrainte d'unicité sur UserRight (genre `validates :user_id, presence: true, uniqueness: { scope: :antenne_id }`)
- revoir l'import des Antennes, pour n'ajouter le manager importé que s'il n'est pas déjà manager de l'antenne

+ un script pour supprimer tous les doublons existants

2022-04-08 07:36 UTC, clairezed requested changes
Cf le commentaire laissé dans le code

2022-04-11 14:08 UTC, LucienMLD commented on app/models/antenne.rb
> +  has_many :managers, -> { distinct }, through: :user_rights_manager, source: :user, inverse_of: :managed_antennes
c'est vrai que je suis allée un peu vite là

2022-04-11 15:32 UTC, LucienMLD commented on db/migrate/20220411140218_deduplicate_antenne_managers.rb
> +        while same_managers.count > 1 do
on dirait un peu un script fait par un enfant, mais ça fonctionne

2022-04-11 15:52 UTC, merged